<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Seoul CURA Healthcare Center</name>
   <tag></tag>
   <elementGuidId>45eb15b6-7460-4e5b-aad1-6d83dfd2fca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#facility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='facility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c11f72cb-0bb6-4758-9e14-1164d24af243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>facility</value>
      <webElementGuid>7e146449-6597-48ea-bb4a-63939c573b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seoul CURA Healthcare Center</value>
      <webElementGuid>aaf38eac-b2b8-4f9a-9ca0-b2e19bba1604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facility&quot;)</value>
      <webElementGuid>42b9228a-a557-4801-85f3-14a21e45f19d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='facility']</value>
      <webElementGuid>551583c8-6e75-4bc0-8898-36366356cd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='history']/div/div[2]/div/div/div[2]/div[2]/p</value>
      <webElementGuid>cc9ead7f-03a1-41f8-8b45-10375ddfd12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>0b7dd484-64ee-455b-9220-c39d722fb7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'facility' and (text() = 'Seoul CURA Healthcare Center' or . = 'Seoul CURA Healthcare Center')]</value>
      <webElementGuid>5dcffb7e-9ddf-44fc-b656-ff09cd8c6249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
